#!/bin/sh
# docker-entrypoint.sh
# Injects BACKEND_URL env variable into the frontend at container start time,
# then launches both the Node backend and the static file server.

set -e

BACKEND_URL="${BACKEND_URL:-http://localhost:3000/compile}"

echo "==> Injecting BACKEND_URL=${BACKEND_URL} into frontend..."

# Write a tiny config script that runner.js will read at runtime.
# This avoids a build step — the value is set fresh every container start.
cat > /app/frontend/env-config.js <<EOF
// Auto-generated by docker-entrypoint.sh — do not edit manually.
window.__CPP_SHELL_BACKEND_URL__ = "${BACKEND_URL}";
EOF

echo "==> Starting backend (Express on :3000) and frontend (serve on :8080)..."

exec concurrently \
  --names "backend,frontend" \
  --prefix-colors "cyan,magenta" \
  "node /app/backend/server.js" \
  "serve -s /app/frontend -l 8080"
